---
# Create swap immediately with 'register' commands vs 'notify', so later plays
# don't fail due to insufficent memory
- name: swap - Verify swap status
  stat: path={{ swapfile_location }}
  register: swap_status

- name: swap - Create swapfile
  command: dd if=/dev/zero of={{ swapfile_location }} bs=1M count={{ swapfile_size }}
  become: yes
  when: swap_status.stat.exists == False

- name: swap - Set permissions
  file: path={{ swapfile_location }} owner=root group=root mode=600
  become: yes
  when: swap_status.stat.exists == False or (swap_status.stat.exists == true and swap_status.stat.mode != 0600)

- name: swap - Format swapfile
  command: mkswap {{ swapfile_location }}
  become: yes
  when: swap_status.stat.exists == False

- name: swap - Enable
  command: swapon {{ swapfile_location }}
  become: yes
  when: swap_status.stat.exists == False

- name: swap - Persist to fstab
  mount: name=none src={{ swapfile_location }} fstype=swap opts=defaults passno=0 dump=0 state=present
  become: yes
  when: swap_status.stat.exists == False