---
- name: Add ssh users
  become: yes
  user: name={{ item.name }}
        password={{ item.password }}
        groups={{ item.groups }}
        state=present
  with_items: "{{ ssh_users }}"

- name: Add ssh keys
  become: yes
  authorized_key: user={{ item.name }} key="{{ item.key }}"
  with_items: "{{ ssh_users }}"

- name: configure sudo for wheel group
  become: yes
  lineinfile:
    dest: /etc/sudoers.d/wheel
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    state: present
    create: yes
    validate: 'visudo -cf %s'
