---
# Install EPEL and upgrade all existing packages, or installing user specified packages may fail
- name: packages - Upgrade existing to latest
  package: name=* state=latest
  become: yes

- name: packages - Install EPEL repo
  package: name=epel-release state=latest
  become: yes

- name: packages - Install user defaults
  package: name="{{ item }}" state=present
  with_items: "{{ default_packages }}"
  become: yes
  notify:
    - update mlocate db