---
- name: Install SELinux
  package: name="{{ item }}" state=present
  with_items:
    - selinux-policy
    - selinux-policy-targeted
  become: yes

- name: Configure SELinux
  selinux: policy={{ selinux_type }} state={{ selinux_enforcement }}
  become: yes
  notify:
    - reboot server