---
- name: Harden ssh configuration
  become: yes
  lineinfile:
    dest: "{{ ssh_config_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backrefs: yes
  with_items:
    - regexp: "^#?PasswordAuthentication"
      line: "PasswordAuthentication {{ ssh_password_authentication }}"
    - regexp: "^#?PermitRootLogin"
      line: "PermitRootLogin {{ ssh_permit_root_login }}"
  notify:
    - reload sshd
  tags: ['bootstrap', 'security']

# A custom SSH port requires multiple changes, including configuring SELinux
# and firewalld to accept the new port
- name: Configure SSH port
  become: yes
  lineinfile:
    dest: "{{ ssh_config_path }}"
    regexp: "^#?Port"
    line: "Port {{ ssh_port }}"
  notify:
    - selinux - validate ssh port
    - firewalld - set ssh port
    - firewalld - remove default ssh service
    - reload sshd
  tags: ['bootstrap', 'security']